[versions]
agp = "8.7.3"
kotlin = "2.0.21"
compose = "1.9.0"
wearCompose = "1.6.2"
activityCompose = "1.10.0"
shirokowear = "0.1.0-SNAPSHOT"
lunar = "1.7.7"
kotlinxSerialization = "1.7.3"
junit = "4.13.2"
androidxTestJunit = "1.2.1"

[libraries]
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
wear-compose-material3 = { module = "androidx.wear.compose:compose-material3", version.ref = "wearCompose" }
wear-compose-foundation = { module = "androidx.wear.compose:compose-foundation", version.ref = "wearCompose" }
shirokowear-ui = { module = "io.github.jinlinahida:shirokowear-ui", version.ref = "shirokowear" }
shirokowear-navigation = { module = "io.github.jinlinahida:shirokowear-navigation", version.ref = "shirokowear" }
lunar = { module = "cn.6tail:lunar", version.ref = "lunar" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerialization" }

junit = { module = "junit:junit", version.ref = "junit" }
androidx-test-junit = { module = "androidx.test.ext:junit", version.ref = "androidxTestJunit" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
